"""
Dados reais do Haxta (EK), exportados do Cyclopedia do proprio personagem
in-game pelo usuario em 2026-07-16. Usado so no seed inicial - depois de
seedado, o progresso e editavel pela interface e vive no banco.
"""

QUEST_LINES_COMPLETED = [
    "20 Years a Cook", "Between the Lines", "Blood Brothers",
    "Children of the Revolution", "Dark Trails", "Feaster of Souls",
    "Ferumbras' Ascendant", "Heart of Destruction", "Hero of Rathleton",
    "In Service Of Yalahar", "Sea of Light", "Shadows of Yalahar",
    "Soul War", "The Ape City", "The Beginning",
    "The Djinn War - Marid Faction", "The First Dragon", "The Ice Islands",
    "The Inquisition", "The New Frontier", "The Pits of Inferno",
    "The Postman Missions", "The Queen of the Banshees",
    "The Shattered Isles", "The Thieves Guild", "What a foolish Quest",
    "Wrath of the Emperor",
]

TITLES_UNLOCKED = [
    "Aeternal", "Beastly", "Beastrider (Grade 1)", "Beastrider (Grade 2)",
    "Boss Destroyer", "Creature of Habit (Grade 1)", "Creature of Habit (Grade 2)",
    "Creature of Habit (Grade 3)", "Creature of Habit (Grade 4)",
    "Creature of Habit (Grade 5)", "Cyclopscamper", "Demondoom",
    "Dragondouser", "Drakenbane", "Hero of Bounac", "Pensive Wanderer",
    "Seasoned Armorer", "Silencer", "Tibia's Topmodel (Grade 1)",
    "Tibia's Topmodel (Grade 2)", "Tibia's Topmodel (Grade 3)",
    "Tibia's Topmodel (Grade 4)", "Time Traveller", "Trolltrasher",
]

ACHIEVEMENTS_UNLOCKED = [
    "A Friend in Need", "A Study in Scarlett", "Allow Cookies?", "Amateur Actor",
    "Annihilator", "Archpostman", "Beach Tamer", "Beak Doctor", "Bearbaiting",
    "Bearhugger", "Beaver Away", "Becoming a Bigfoot", "Berserker", "Beyonder",
    "Bibby's Bloodbath", "Blessed!", "Brutal Politeness", "Buried the Baron",
    "Cake Conqueror", "Call Me Sparky", "Champion of Chazorai", "Chequered Teddy",
    "Choking on Her Venom", "Chorister", "Contender", "Crystal Keeper",
    "Crystals in Love", "Death from Below", "Death in the Depths", "Demonbane",
    "Drama in Darama", "Duked It Out", "Dungeon Cleaner", "Elite Hunter",
    "Ender of the End", "Engine Driver", "Enter zze Draken!", "Errand Runner",
    "Exemplary Citizen", "Explorer", "Fata Morgana", "Final Strike",
    "Follower of Palimuth", "Fool at Heart", "Fountain of Life",
    "Friend of Elves", "Friend of the Apes", "Ghostwhisperer", "Gnome Friend",
    "Gnome Little Helper", "Gnomebane's Bane", "Gnomelike", "Gnomish Art of War",
    "Go with da Lava Flow", "Godslayer", "Golden Sands", "Golem in the Gears",
    "Greenhorn", "Grinding Again", "Happy Farmer", "Hat Hunter",
    "High Inquisitor", "High-Flyer", "His Days are Counted", "Hissing Downfall",
    "Honorary Barbarian", "Honorary Gnome", "Honorary Rascoohan",
    "Hope of the Merudri", "Hunting Permit", "Huntsman", "I Did My Part",
    "I Wanna Fly Away", "Inquisition's Hand", "Joke's on You",
    "Just Cracked Me Up!", "Just in Time", "Keeper of the Flame",
    "Lacewing Catcher", "Lion King", "Lion's Den Explorer", "Lionheart",
    "Little Adventure", "Little Ball of Wool", "Lost Palace Raider",
    "Loyal Lad", "Lucid Dreamer", "Lucky Horseshoe", "Mageslayer",
    "Mainstreet Nightmare", "Marid Ally", "Master Thief", "Master of the Nexus",
    "Matchmaker", "Millennial Falcon", "Mind the Dog!", "Moth Whisperer",
    "Natural Born Cowboy", "Natural Sweetener", "Nightmare Knight",
    "Nightmare Walker", "No More Hiding", "Nothing Can Stop Me",
    "Nothing but Hot Air", "One Foot Vs. Many", "One Less",
    "Out of the Stone Age", "Over the Moon", "Pecking Order", "Perfect Fool",
    "Pied Piper", "Plant vs. Minos", "Potion Addict", "Power of Words",
    "Prison Break", "Prospectre", "Rathleton Citizen", "Rathleton Commoner",
    "Rathleton Inhabitant", "Rathleton Squire", "Recognised Trader",
    "Release the Kraken", "Robo Chop", "Rock Me to Sleep", "Rocket in Pocket",
    "Rollercoaster", "Rumble in the Plant", "Ruthless", "Safely Stored Away",
    "Scrapper", "Sea Scout", "Seasoned Adventurer", "Secret Agent",
    "Ship's Kobold", "Si, Ariki!", "Skilled Hunter", "Slayer of Chikhaton",
    "Snowbunny", "Soul Crusher", "Spectulation", "Spin-Off", "Spore Hunter",
    "Steampunked", "Substitute Tinker", "Swift Death", "Teamplayer",
    "The Drowned Sea God", "The First of Many", "The Picky Pig",
    "The Professor's Nut", "The Right Tone", "The Serpent's Bride",
    "The Undertaker", "Tied the Knot", "Top CGB Agent", "Trail of the Ape God",
    "Twisted Mutation", "Vive la Resistance", "Warlock", "Warlord of Svargrond",
    "Wayfarer", "Wedding Planner", "Well Roared, Lion!", "Wild Warrior",
    "Woodcarver", "Yalahari of Wisdom",
]

IMBUEMENTS_UNLOCKED = [
    "Powerful Bash", "Powerful Blockade", "Powerful Chop",
    "Powerful Cloud Fabric", "Powerful Demon Presence", "Powerful Dragon Hide",
    "Powerful Electrify", "Powerful Epiphany", "Powerful Featherweight",
    "Powerful Frost", "Powerful Lich Shroud", "Powerful Precision",
    "Powerful Punch", "Powerful Quara Scale", "Powerful Reap",
    "Powerful Scorch", "Powerful Slash", "Powerful Snake Skin",
    "Powerful Strike", "Powerful Swiftness", "Powerful Vampirism",
    "Powerful Venom", "Powerful Void",
]

# nome (bate com reference_data.CHARMS), grade
ACTIVE_CHARMS = [
    ("Divine Wrath II", 2),
    ("Enflame", 1),
    ("Freeze II", 2),
    ("Savage Blow", 1),
    ("Gut", 3),
]

# nome, step (0=nada, 1=Bane, 2=Archfoe, 3=Nemesis), kills
BOSSTIARY_PROGRESS = [
    ("Abyssador", 2, 33), ("Ahau", 2, 41), ("Amenef The Burning", 3, 60),
    ("Annihilon", 0, 2), ("Anomaly", 3, 169), ("Arthei", 0, 1),
    ("Ascending Ferumbras", 3, 10), ("Bibby Bloodbath", 1, 9),
    ("Black Knight", 0, 1), ("Black Vixen", 3, 93), ("Blight Mariner", 2, 21),
    ("Bloodback", 3, 75), ("Boreth", 0, 1), ("Bragrumol", 0, 3),
    ("Brain Head", 0, 2), ("Brokul", 0, 4), ("Chikhaton", 1, 1),
    ("Count Vlarkorth", 2, 33), ("Custodian", 0, 1), ("Darkfang", 3, 72),
    ("Dazed Leaf Golem", 0, 3), ("Death Priest Shargon", 0, 1),
    ("Deathstrike", 2, 32), ("Deep Terror", 0, 1), ("Diseased Bill", 0, 3),
    ("Diseased Dan", 0, 4), ("Diseased Fred", 0, 3), ("Dragon Pack", 1, 15),
    ("Drume", 3, 210), ("Duke Krule", 2, 37), ("Earl Osam", 2, 37),
    ("Enusat The Onyx Wing", 0, 1), ("Eradicator", 3, 164),
    ("Essence Of Malice", 0, 3), ("Faceless Bane", 2, 29), ("Feroxa", 1, 1),
    ("Gaffir", 0, 3), ("Gaz'haragoth", 1, 1), ("Gelidrazah The Frozen", 2, 28),
    ("Ghazbaran", 1, 1), ("Glitterscale", 0, 1), ("Gnomevil", 2, 32),
    ("Golgordan", 0, 2), ("Gorga", 1, 26), ("Goshnar's Cruelty", 0, 1),
    ("Goshnar's Greed", 0, 3), ("Goshnar's Hatred", 0, 1),
    ("Goshnar's Malice", 0, 1), ("Goshnar's Megalomania", 1, 1),
    ("Goshnar's Spite", 0, 1), ("Grand Canon Dominus", 0, 8),
    ("Grand Chaplain Gaunder", 0, 5), ("Grand Commander Soeren", 1, 64),
    ("Grand Master Oberon", 3, 258), ("Grand Mother Foulscale", 3, 5),
    ("Guard Captain Quaid", 0, 2), ("Hellgorak", 0, 4), ("Heoni", 0, 6),
    ("Inkwing", 1, 39), ("Irgix The Flimsy", 3, 61), ("Jailer", 2, 129),
    ("Kalyassa", 2, 29), ("Katex Blood Tongue", 3, 127), ("King Zelos", 1, 6),
    ("Kroazur", 2, 181), ("Kusuma", 2, 35), ("Lady Tenebris", 1, 9),
    ("Latrivan", 0, 2), ("Lersatio", 0, 2), ("Lizard Gate Guardian", 3, 5),
    ("Lloyd", 1, 8), ("Lord Azaram", 2, 35), ("Mad Mage", 0, 1),
    ("Madareth", 0, 2), ("Marziel", 0, 1), ("Mazoran", 0, 2),
    ("Megasylvan Yselda", 1, 12), ("Melting Frozen Horror", 1, 7),
    ("Mozradek", 0, 2), ("Neferi The Spy", 3, 64), ("Orshabaal", 1, 1),
    ("Outburst", 3, 166), ("Plagirath", 1, 5), ("Preceptor Lazare", 2, 118),
    ("Professor Maxxen", 0, 1), ("Ragiaz", 0, 2),
    ("Ratmiral Blackwhiskers", 1, 17), ("Ravenous Hunger", 2, 55),
    ("Razzagorn", 0, 2), ("Realityquake", 3, 63), ("Rupture", 3, 61),
    ("Scarlett Etzel", 3, 159), ("Shadowpelt", 3, 70), ("Sharpclaw", 3, 72),
    ("Shulgrax", 0, 2), ("Sir Baeloc", 2, 37), ("Sir Leonard", 1, 36),
    ("Sir Nictros", 2, 35), ("Sister Hetai", 3, 61),
    ("Soul Of Dragonking Zyrtarch", 1, 5), ("Srezz Yellow Eyes", 3, 128),
    ("Sugar Daddy", 0, 6), ("Tarbaz", 0, 2), ("Tazhadur", 2, 29),
    ("Tentugly", 2, 24), ("Thaian", 0, 3), ("Thawing Dragon Lord", 0, 3),
    ("The Baron From Below", 0, 1), ("The Count Of The Core", 0, 1),
    ("The Dread Maiden", 1, 16), ("The Duke Of The Depths", 0, 1),
    ("The Enraged Thorn Knight", 1, 6), ("The False God", 0, 1),
    ("The Fear Feaster", 1, 13), ("The First Dragon", 3, 7),
    ("The Flaming Orchid", 3, 60), ("The Lord Of The Lice", 0, 2),
    ("The Moonlight Aster", 3, 60), ("The Pale Worm", 2, 27),
    ("The Percht Queen", 1, 2), ("The Ravager", 0, 1),
    ("The Shatterer", 0, 2), ("The Souldespoiler", 0, 3),
    ("The Time Guardian", 1, 9), ("The Unwelcome", 1, 13),
    ("The Welter", 1, 1), ("The Winter Bloom", 3, 62),
    ("Timira The Many-Headed", 3, 246), ("Tropical Desolator", 2, 21),
    ("Unaz The Mean", 3, 62), ("Urmahlullu The Weakened", 3, 81),
    ("Ushuriel", 0, 2), ("Utua Stone Sting", 3, 128),
    ("Vok The Freakish", 3, 61), ("Willi Wasp", 1, 1),
    ("World Devourer", 3, 7), ("Wrathful Archivist", 2, 25),
    ("Xogixath", 0, 2), ("Yirkas Blue Scales", 3, 134), ("Zamulosh", 0, 2),
    ("Zorvorax", 2, 29), ("Zugurosh", 0, 2), ("Zulazza The Corruptor", 1, 1),
]
